name: Kubescape scanning for misconfigurations
on: [pull_request, workflow_dispatch]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      
      - name: Scan with Kubescape
        uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: sarif
          outputFile: results
          account: ${{ secrets.KUBESCAPE_ACCOUNT }}
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          fixFiles: true

      - name: Annotation
        if: ${{ success() }} || ${{ failure() }}
        uses: yeaung276/sarif-annotator@1.0.1
        with: 
          sarif_path: results.sarif
          
      - name: Clean workspace
        uses: AutoModality/action-clean@v1
 
